
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(101,'HCL',700.55);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(102,'TCS',456.55);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(103,'WIPRO',800.06);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(104,'IBM',325.78);
INSERT INTO STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE) VALUES(105,'LIC',966.32);
