
server:  port: 9595
  
spring:  application:    name: Hi-Rest-Api-Client-2
      boot:    admin:      client:        url: http://localhost:8888
        
management:  endpoints:    web:      exposure:        include: '*'